apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-typesense
  labels:
    {{- include "app.labels" . | nindent 4 }}
    component: typesense
spec:
  type: {{ .Values.typesense.service.type }}
  ports:
    - port: {{ .Values.typesense.service.port }}
      targetPort: {{ .Values.typesense.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: typesense