apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-ui
  labels:
    {{- include "app.labels" . | nindent 4 }}
    component: ui
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    component: ui