---
- name: Cleaning your application images and deployment
  block:
    - name: Setup environment
      include_tasks: setup.yml

    - name: Remove application from  Kubernetes
      include_tasks: remove_app.yml

    - name: Remove images
      include_tasks: remove_images.yml

  always:
    - name: Cleanup resources
      include_tasks: cleanup.yml
