---
- name: Configuring cluster
  block:
    - import_tasks: configure-cluster.yml
      tags: system
    - name: Send to Slack (success)
      when: slack_notification
      community.general.slack:
        token: "{{ setup.SLACK_OAUTH }}"
        msg: |
          :white_check_mark: *Cluster setup SUCCESSFUL!*
          
          *Details:*
          • Completed: {{ ansible_date_time.iso8601 }}
          • Started by: {{ ansible_user | default('ansible') }}
        channel: "{{ slack_channel }}"
        username: "Ansible"
        color: good
      delegate_to: localhost
  rescue:
    - name: Send to Slack (failure)
      when: slack_notification
      community.general.slack:
        token: "{{ setup.SLACK_OAUTH }}"
        msg: |
          :x: *Cluster setup "failed*
          Error: {{ ansible_failed_result.msg | default('Unknown error') }}
        channel: "{{ slack_channel }}"
        username: "Ansible"
        color: danger
      delegate_to: localhost
