version: "2.4"
services:
  server:
    mem_limit: 4g
    environment:
      - ACCOMPAGNATEUR_ENV=production
      - ACCOMPAGNATEUR_LOG_LEVEL=info
      - ACCOMPAGNATEUR_LOG_DESTINATIONS=stdout,sql,slack
      - ACCOMPAGNATEUR_PUBLIC_URL=https://api.exposition.inserjeunes.beta.gouv.fr
      - ACCOMPAGNATEUR_MONGODB_URI={{ vault.ACCOMPAGNATEUR_MONGODB_URI }}
      - ACCOMPAGNATEUR_SLACK_WEBHOOK_URL={{ vault.ACCOMPAGNATEUR_SLACK_WEBHOOK_URL }}
      - CATALOGUE_APPRENTISSAGE_USERNAME={{ vault.CATALOGUE_APPRENTISSAGE_USERNAME }}
      - CATALOGUE_APPRENTISSAGE_PASSWORD={{ vault.CATALOGUE_APPRENTISSAGE_PASSWORD }}
      - ACCOMPAGNATEUR_POSTGRES_URI={{ vault.ACCOMPAGNATEUR_POSTGRES_URI }}
      - ACCOMPAGNATEUR_POSTGRES_CA={{ vault.ACCOMPAGNATEUR_POSTGRES_CA }}
      - DATABASE_URL={{ vault.ACCOMPAGNATEUR_POSTGRES_URI }}

  ui:
    environment:
      - NEXT_PUBLIC_LOGROCKET=jf5zdt/cest-qui-le-pro
      - NEXT_PUBLIC_MATOMO_SITE_ID=143
      - NEXT_PUBLIC_MATOMO_URL=https://stats.beta.gouv.fr
      - NEXT_PUBLIC_MATOMO_ENABLE=true
    build:
      args:
        - NEXT_PUBLIC_LOGROCKET=jf5zdt/cest-qui-le-pro
        - NEXT_PUBLIC_MATOMO_SITE_ID=143
        - NEXT_PUBLIC_MATOMO_URL=https://stats.beta.gouv.fr
        - NEXT_PUBLIC_MATOMO_ENABLE=true

  typesense:
    mem_limit: 4g

  metabase:
    mem_limit: 4g
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_CONNECTION_URI={{ vault.ACCOMPAGNATEUR_POSTGRESQL_METABASE }}
      - MB_SITE_URL=https://exposition.inserjeunes.beta.gouv.fr/metabase
