version: "2.4"
services:
  server:
    mem_limit: 4g
    environment:
      - ACCOMPAGNATEUR_ENV=production
      - ACCOMPAGNATEUR_LOG_LEVEL=info
      - ACCOMPAGNATEUR_LOG_DESTINATIONS=stdout,mongodb,slack
      - ACCOMPAGNATEUR_PUBLIC_URL=https://api.exposition.inserjeunes.beta.gouv.fr
      - ACCOMPAGNATEUR_MONGODB_URI={{ vault.ACCOMPAGNATEUR_MONGODB_URI }}
      - ACCOMPAGNATEUR_SLACK_WEBHOOK_URL={{ vault.ACCOMPAGNATEUR_SLACK_WEBHOOK_URL }}
      - CATALOGUE_APPRENTISSAGE_USERNAME={{ vault.CATALOGUE_APPRENTISSAGE_USERNAME }}
      - CATALOGUE_APPRENTISSAGE_PASSWORD={{ vault.CATALOGUE_APPRENTISSAGE_PASSWORD }}

  metabase:
    mem_limit: 4g
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_CONNECTION_URI={{ vault.ACCOMPAGNATEUR_POSTGRESQL_METABASE }}
      - MB_SITE_URL=https://exposition.inserjeunes.beta.gouv.fr/metabase

  mongodb:
    mem_limit: 6g
