

global:
  suspend: false
service:
  image:
    repository: ghcr.io/mission-apprentissage/graphhopper
    tag: latest
    pullPolicy: Always
    custom:
      enabled: true
      version: ghcr.io/mission-apprentissage/graphhopper:latest
security:
  password: changeme
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
imagePullSecrets:
  - name: github-registry
init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
  regionInitCheckSum: ''
  personalInit: ''
  personalInitArgs: ''
extraEnvVars:
  - name: GRAPHHOPPER_MEMORY_LIMIT
    value: "96g"
  # Add more environment variables as needed
s3:
  enabled: false
  secretName: ''
  accessKeyId: ''
  endpoint: ''
  defaultRegion: ''
  secretAccessKey: ''
  sessionToken: ''
  pathStyleAccess: false
  workingDirectoryPath: ''
vault:
  enabled: false
  secretName: ''
  token: ''
  url: ''
  mount: ''
  secret: ''
  directory: ''
git:
  enabled: true
  secretName: ''
  name: ''
  email: ''
  cache: ''
  branch: ''
repository:
  configMapName: ''
  pipRepository: ''
  condaRepository: ''
discovery:
  hive: true
  mlflow: true
  metaflow: true
  chromadb: true
hive:
  secretName: ''
mlflow:
  secretName: ''
metaflow:
  secretName: ''
chromadb:
  secretName: ''
coresite:
  secretName: ''
replicaCount: 1
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
environment:
  user: onyxia
  group: users
kubernetes:
  enabled: true
  role: view
podAnnotations: {}
podSecurityContext:
  fsGroup: 100
securityContext: {}
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8989
  user:
    enabled: false
    port: 8989
    ports: []
ingress:
  enabled: false
  tls: true
  ingressClassName: ''
  annotations: []
  hostname: chart-example.local
  userHostname: chart-example-user.local
  useCertManager: false
  certManagerClusterIssuer: ''
  useTlsSecret: false
route:
  enabled: false
  annotations: []
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
  wildcardPolicy: None
resources:
  requests:
    cpu: 20200m
    memory: 126Gi
  limits:
    cpu: 30000m
    memory: 143Gi
persistence:
  enabled: true
  size: 100Gi
  accessMode: ReadWriteOnce
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
startupProbe:
  failureThreshold: 60
  initialDelaySeconds: 6400 # time to import data in graphhopper
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 2
userPreferences:
  darkMode: false
  language: en
openshiftSCC:
  enabled: false
  scc: ''
proxy:
  enabled: false
  noProxy: ''
  httpProxy: ''
  httpsProxy: ''
certificates: {}
message:
  fr: ''
  en: ''