

global:
  suspend: false
service:
  image:
    repository: yse0gvzk.c1.gra9.container-registry.ovh.net/private/graphhopper
    tag: latest
    pullPolicy: Always
    custom:
      enabled: true
      version: yse0gvzk.c1.gra9.container-registry.ovh.net/private/graphhopper:latest
ingress:
  enabled: true
  hostname: graphhopper-cqlp.lab.sspcloud.fr
  tls: true
  ingressClassName: 'nginx'  # specify your ingress controller class name
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "128m"
  userHostname: chart-example-user.local
  useCertManager: false
  certManagerClusterIssuer: ''
  useTlsSecret: false
security:
  password: changeme
  networkPolicy:
    enabled: false
    from: []
  allowlist:
    enabled: false
    ip: 0.0.0.0/0
imagePullSecrets:
  - name: my-registry
init:
  standardInitPath: /opt/onyxia-init.sh
  regionInit: ''
  regionInitCheckSum: ''
  personalInit: ''
  personalInitArgs: ''
extraEnvVars:
  - name: GRAPHHOPPER_MEMORY_LIMIT
    value: "96g"
  - name: GRAPHHOPPER_CPU_COUNT
    value: "20"
  - name: GTFS_MODALITE
    value: "transport"
s3:
  enabled: false
  secretName: ''
  accessKeyId: ''
  endpoint: ''
  defaultRegion: ''
  secretAccessKey: ''
  sessionToken: ''
  pathStyleAccess: false
  workingDirectoryPath: ''
vault:
  enabled: false
  secretName: ''
  token: ''
  url: ''
  mount: ''
  secret: ''
  directory: ''
git:
  enabled: true
  secretName: ''
  name: ''
  email: ''
  cache: ''
  branch: ''
repository:
  configMapName: ''
  pipRepository: ''
  condaRepository: ''
discovery:
  hive: true
  mlflow: true
  metaflow: true
  chromadb: true
hive:
  secretName: ''
mlflow:
  secretName: ''
metaflow:
  secretName: ''
chromadb:
  secretName: ''
coresite:
  secretName: ''
replicaCount: 1
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
environment:
  user: onyxia
  group: users
kubernetes:
  enabled: true
  role: view
# Pod termination settings
podTerminationGracePeriod: 1200 # 5 minutes grace period

# Container lifecycle hooks
lifecycleHooks:
  preStop:
    exec:
      command:
        - "/bin/sh"
        - "-c"
        - |
          PID=$(ps aux | grep graphhopper-web | grep -v grep | awk '{print $1}')
          [ -n "$PID" ] && kill -15 $PID && sleep 30

# StatefulSet update strategy
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    partition: 0
podSecurityContext:
  fsGroup: 100
securityContext: {}
networking:
  type: ClusterIP
  clusterIP: None
  service:
    port: 8989
  user:
    enabled: false
    port: 8989
    ports: []
route:
  enabled: false
  annotations: []
  hostname: chart-example.local
  userHostname: chart-example-user.local
  tls:
    termination: edge
  wildcardPolicy: None
resources:
  requests:
    cpu: 20200m
    memory: 126Gi
  limits:
    cpu: 30000m
    memory: 143Gi
persistence:
  enabled: true
  size: 200Gi
  accessMode: ReadWriteOnce
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
startupProbe:
  failureThreshold: 720
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 20
userPreferences:
  darkMode: false
  language: en
openshiftSCC:
  enabled: false
  scc: ''
proxy:
  enabled: false
  noProxy: ''
  httpProxy: ''
  httpsProxy: ''
certificates: {}
message:
  fr: ''
  en: ''