---

- hosts: all
  vars:
    app_name: "cqlp"
    app_version: "{{ APP_VERSION | lower | regex_replace('[^a-z0-9-]', '-') | regex_replace('^-+', '') | regex_replace('-+$', '') | truncate(63, True, '') }}"
    image_to_remove: ["ui", "server"]
    docker_registry: "{{ setup.DOCKER_REGISTRY}}"
    docker_registry_path: "{{ setup.DOCKER_REGISTRY_PATH | default('/') }}"
    docker_username: "{{ setup.DOCKER_USERNAME }}"
    docker_password: "{{ setup.DOCKER_PASSWORD }}"
    helm_timeout: "600s"
    helm_wait: true
    delete_namespace: "{{ (env_type == 'dev') | bool }}"

    slack_notification: true
  roles:
    - clean
