version: "2.4"
services:
  reverse_proxy:
    ports:
      - 443:443
    volumes:
      - /opt/accompagnateur/data/nginx:/data
      - /opt/accompagnateur/data/ssl:/ssl:ro
      - /opt/accompagnateur/.overrides/reverse_proxy/location_proxima.conf.template:/etc/nginx/templates/includes/location_proxima.conf.template
    environment:
      - SERVER_NAME={{dns_name}}
      - SERVER_NAME_ALTERNATIVE={{dns_name_alternative}}
      - NGINX_ALWAYS_TLS_REDIRECT=true
      - PROXY_SSL_CERT=/ssl/fullchain.pem
      - PROXY_SSL_CERT_KEY=/ssl/privkey.pem

  server:
    volumes:
      - /opt/accompagnateur/data/server:/data
    environment:
      - EXPOSITION_API_USERNAME={{ vault.EXPOSITION_API_USERNAME }}
      - EXPOSITION_API_PASSWORD={{ vault.EXPOSITION_API_PASSWORD}}
      - RCO_BUCKET_ENDPOINT={{ vault.RCO_BUCKET_ENDPOINT }}
      - RCO_BUCKET_REGION={{ vault.RCO_BUCKET_REGION }}
      - RCO_BUCKET_ACCESS_KEY={{ vault.RCO_BUCKET_ACCESS_KEY }}
      - RCO_BUCKET_SECRET_KEY={{ vault.RCO_BUCKET_SECRET_KEY }}
      - RCO_BUCKET_NAME={{ vault.RCO_BUCKET_NAME }}

  mongodb:
    volumes:
      - /opt/accompagnateur/data/mongodb/db:/data/db
      - /opt/accompagnateur/data/mongodb/configdb:/data/configdb
      - /opt/accompagnateur/data/mongodb/backups:/data/backups
      - /opt/accompagnateur/.overrides/mongodb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  metabase:
    volumes:
      - /opt/accompagnateur/data/metabase:/data
    environment:
      - MB_DB_FILE=/data/metabase.db

  ui:
    environment:
      - METABASE_SECRET_KEY={{ vault.METABASE_SECRET_KEY }}
      - EXPOSITION_API_BASE_URL=https://api.exposition.inserjeunes.beta.gouv.fr
      - NEXT_PUBLIC_DOMAIN={{dns_name}}
      - NEXT_PUBLIC_API_BASE_URL=/api
      - NEXT_PUBLIC_ACCOMPAGNATEUR_API_BASE_URL=/api
      - NEXT_PUBLIC_EXPOSITION_WIDGET_HASH=405gzo3im03r8sun
      - NEXT_PUBLIC_EXPOSITION_API_BASE_URL=https://api.exposition.inserjeunes.beta.gouv.fr
      - NEXT_PUBLIC_SIRIUS_API_BASE_URL=https://sirius.inserjeunes.beta.gouv.fr
    build:
      args:
        - METABASE_SECRET_KEY={{ vault.METABASE_SECRET_KEY }}
        - EXPOSITION_API_BASE_URL=https://api.exposition.inserjeunes.beta.gouv.fr
        - NEXT_PUBLIC_DOMAIN={{dns_name}}
        - NEXT_PUBLIC_API_BASE_URL=/api
        - NEXT_PUBLIC_ACCOMPAGNATEUR_API_BASE_URL=/api
        - NEXT_PUBLIC_EXPOSITION_WIDGET_HASH=405gzo3im03r8sun
        - NEXT_PUBLIC_EXPOSITION_API_BASE_URL=https://api.exposition.inserjeunes.beta.gouv.fr
        - NEXT_PUBLIC_SIRIUS_API_BASE_URL=https://sirius.inserjeunes.beta.gouv.fr
