version: "2.4"
services:
  server:
    environment:
      - ACCOMPAGNATEUR_ENV=recette
      - ACCOMPAGNATEUR_LOG_LEVEL=info
      - ACCOMPAGNATEUR_LOG_DESTINATIONS=stdout,mongodb
      - ACCOMPAGNATEUR_PUBLIC_URL=https://api.{{ dns_name }}
      - ACCOMPAGNATEUR_MONGODB_URI=mongodb://accompagnateur:{{ vault.ACCOMPAGNATEUR_MONGODB_USER_PASSWORD }}@mongodb:27017/accompagnateur?authSource=admin&retryWrites=true&w=majority
      - CATALOGUE_APPRENTISSAGE_USERNAME={{ vault.CATALOGUE_APPRENTISSAGE_USERNAME }}
      - CATALOGUE_APPRENTISSAGE_PASSWORD={{ vault.CATALOGUE_APPRENTISSAGE_PASSWORD }}
      - ACCOMPAGNATEUR_POSTGRES_URI={{ vault.ACCOMPAGNATEUR_RECETTE_POSTGRES_URI }}
      - ACCOMPAGNATEUR_POSTGRES_CA={{ vault.ACCOMPAGNATEUR_RECETTE_POSTGRES_CA }}
      - DATABASE_URL={{ vault.ACCOMPAGNATEUR_RECETTE_POSTGRES_URI }}

  ui:
    environment:
      - NEXT_PUBLIC_LOGROCKET=jf5zdt/cest-qui-le-pro-recette
    build:
      args:
        - NEXT_PUBLIC_LOGROCKET=jf5zdt/cest-qui-le-pro-recette

  metabase:
    environment:
      - MB_SITE_URL=https://{{ dns_name }}/metabase
