version: "2.4"
services:
  server:
    environment:
      - ACCOMPAGNATEUR_ENV=recette
      - ACCOMPAGNATEUR_LOG_LEVEL=info
      - ACCOMPAGNATEUR_LOG_DESTINATIONS=stdout,sql
      - ACCOMPAGNATEUR_PUBLIC_URL=https://api.{{ dns_name }}
      - CATALOGUE_APPRENTISSAGE_USERNAME={{ vault.CATALOGUE_APPRENTISSAGE_USERNAME }}
      - CATALOGUE_APPRENTISSAGE_PASSWORD={{ vault.CATALOGUE_APPRENTISSAGE_PASSWORD }}
      - ACCOMPAGNATEUR_POSTGRES_URI={{ vault.ACCOMPAGNATEUR_RECETTE_POSTGRES_URI }}
      - ACCOMPAGNATEUR_POSTGRES_CA={{ vault.ACCOMPAGNATEUR_RECETTE_POSTGRES_CA }}
      - DATABASE_URL={{ vault.ACCOMPAGNATEUR_RECETTE_POSTGRES_URI }}

  ui:
    environment:
      - NEXT_PUBLIC_LOGROCKET=jf5zdt/cest-qui-le-pro-recette
      - NEXT_PUBLIC_EXPOSITION_WIDGET_HASH=405gzn2ilvcebavw
      - NEXT_PUBLIC_EXPOSITION_API_BASE_URL=https://api.recette.exposition.inserjeunes.incubateur.net
      - NEXT_PUBLIC_SIRIUS_API_BASE_URL=https://sirius-recette.inserjeunes.beta.gouv.fr
      - NEXT_PUBLIC_MATOMO_SITE_ID=183
      - NEXT_PUBLIC_MATOMO_URL=https://stats.beta.gouv.fr
      - NEXT_PUBLIC_MATOMO_ENABLE=true
    build:
      args:
        - NEXT_PUBLIC_LOGROCKET=jf5zdt/cest-qui-le-pro-recette
        - NEXT_PUBLIC_EXPOSITION_WIDGET_HASH=405gzn2ilvcebavw
        - NEXT_PUBLIC_EXPOSITION_API_BASE_URL=https://api.recette.exposition.inserjeunes.incubateur.net
        - NEXT_PUBLIC_SIRIUS_API_BASE_URL=https://sirius-recette.inserjeunes.beta.gouv.fr
        - NEXT_PUBLIC_MATOMO_SITE_ID=183
        - NEXT_PUBLIC_MATOMO_URL=https://stats.beta.gouv.fr
        - NEXT_PUBLIC_MATOMO_ENABLE=true

  metabase:
    environment:
      - MB_SITE_URL=https://{{ dns_name }}/metabase
