---
- name: Building and deploying your application
  block:
    - name: Setup environment
      include_tasks: setup.yml

    - name: Deploy to Kubernetes
      include_tasks: deploy.yml

  always:
    - name: Cleanup resources
      include_tasks: cleanup.yml
