---
- name: Create environment files
  block:
    - name: Disable deprecation warnings
      ansible.builtin.set_fact:
        ansible_deprecation_warnings: false
      run_once: true

    - name: Create .env.yaml
      template:
        src: "{{infra_dir}}/.env.yaml.tpl"
        dest: "{{infra_dir}}/.env.yaml"
      no_log: true

    - name: Load .env.yaml
      include_vars:
        file: "{{infra_dir}}/.env.yaml"
        name: env_vars
      no_log: true

    - name: Create temporary kubeconfig
      tempfile:
        state: file
        suffix: .kubeconfig
      register: temp_kubeconfig
      no_log: true

    - name: Decode kubeconfig
      copy:
        content: "{{ setup.KUBECONFIG | b64decode }}"
        dest: "{{ temp_kubeconfig.path }}"
        mode: '0600'
      no_log: true

    - name: Register cleanup items
      set_fact:
        cleanup_files: "{{ cleanup_files | default([]) + [infra_dir + '/.env.yaml', temp_kubeconfig.path] }}"
