---
- name: Create environment files
  block:
    - name: Create .env.yaml
      template:
        src: "{{infra_dir}}/.env.yaml.tpl"
        dest: "{{infra_dir}}/.env.yaml"
      no_log: true

    - name: Load .env.yaml
      include_vars:
        file: "{{infra_dir}}/.env.yaml"
        name: env_vars
      no_log: true

    - name: Create .env file
      template:
        src: "{{infra_dir}}/.env.tpl"
        dest: "{{infra_dir}}/.env"
      vars:
        env_variables: "{{ env_vars.env.server | combine(env_vars.env.ui) }}"
      no_log: true

    - name: Create temporary kubeconfig
      tempfile:
        state: file
        suffix: .kubeconfig
      register: temp_kubeconfig

    - name: Decode kubeconfig
      copy:
        content: "{{ setup.KUBECONFIG | b64decode }}"
        dest: "{{ temp_kubeconfig.path }}"
        mode: '0600'
      no_log: true

    - name: Register cleanup items
      set_fact:
        cleanup_files: "{{ cleanup_files | default([]) + [infra_dir + '/.env.yaml', infra_dir + '/.env', temp_kubeconfig.path] }}"
