habilitations:
  - username: bguerout
    name: Benoît Guérout
    gpg_key: 3D80C46E
    authorized_keys:
      - "https://github.com/bguerout.keys"

  - username: eric
    name: Eric Plaquevent
    gpg_key: F9A12366F49B61DF
    authorized_keys:
      - "https://github.com/ericplaquevent.keys"

  - username: antoine
    name: Antoine Bigard
    gpg_key: AF6496CB
    authorized_keys:
      - "https://github.com/antoinebigard.keys"

  - username: florian
    name: florian de-la-comble
    gpg_key: BE0F1098
    authorized_keys:
      - "https://github.com/flodlc.keys"

  - username: ananda
    name: ananda norindr
    gpg_key: 29D66151
    authorized_keys:
      - "https://github.com/k4st0R.keys"

  - username: yohann
    name: Yohann Gablowski
    gpg_key: 7B3F9F11317FB741
    authorized_keys:
      - "https://github.com/yohanngab.keys"

  - username: lucas
    name: Lucas Détré
    gpg_key: 032D0F5C
    authorized_keys:
      - "https://github.com/LucasDetre.keys"

  - username: marin
    name: Marin Procureur
    gpg_key: 65353FE5
    authorized_keys:
      - "https://github.com/faxaq.keys"

  - username: gaetan
    name: Gaetan BUSATO
    gpg_key: F4FCE790
    authorized_keys:
      - "https://github.com/gBusato.keys"

gpg_keys: "{{ habilitations  | map(attribute='gpg_key', default='') | select() | join(',')}}"
