ARG ACCOMPAGNATEUR_ENV=dev
#From https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile
# Install dependencies only when needed
FROM node:18-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
RUN apk add --no-cache pango-dev g++ make jpeg-dev giflib-dev librsvg-dev
# Install dependencies including Python
RUN apk add --no-cache python3 py3-pip \
    && ln -sf python3 /usr/bin/python \
    && ln -sf pip3 /usr/bin/pip
WORKDIR /app
COPY package.json .
COPY yarn.lock .
COPY shared/package.json shared/
COPY ui/package.json ui/
RUN yarn install --frozen-lockfile

COPY ./shared shared
COPY ./ui ui

WORKDIR /app/ui

CMD ["yarn",  "dev"]