name: Build the application

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: azure/setup-helm@v4.3.0
        id: install
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Ansible
        shell: bash
        run: |
          # sudo apt-get update
          # sudo apt-get install -y ansible
          #python3 -m pip install --upgrade pip
          pip install ansible-core
          pip install requests
          pip install docker
          pip install kubernetes
          pip install PyYAML
      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass.txt
      - name: Set env
        run: echo "VAULT_PASSWORD_FILE=.vault_pass.txt" >> $GITHUB_ENV
      - name: Build with ansible (dev)
        run: |
          bash .infra/scripts/build-app.sh \
            "dev" \
            "${{ github.head_ref || github.ref_name}}"
            - name: Build with ansible (dev)
      - name: Build with ansible (recette)
        run: |
          bash .infra/scripts/build-app.sh \
            "recette" \
            "${{ github.head_ref || github.ref_name}}"