name: Deploying the application

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Merci de préciser un environnement (ex. dev, recette ou production)'
        required: true
      app_version:
         description: 'Merci de préciser une version (correspondra au tag des images docker)'
         required: true
      app_namespace:
        description: 'Merci de préciser un namespace (ex. recette, production ou nom de la branche)'
        required: true

jobs:
  run-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: azure/setup-helm@v4.3.0
        id: install
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Ansible
        shell: bash
        run: |
          # sudo apt-get update
          # sudo apt-get install -y ansible
          #python3 -m pip install --upgrade pip
          pip install ansible-core
          pip install requests
          pip install docker
          pip install kubernetes
          pip install PyYAML
      - name: Create vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass.txt
      - name: Set env
        run: echo "VAULT_PASSWORD_FILE=.vault_pass.txt" >> $GITHUB_ENV
      - name: Run Ansible playbook
        run: |
          bash .infra/scripts/deploy-app.sh \
            "${{ github.event.inputs.env_name }}" \
            "${{ github.event.inputs.app_version }}" \
            "${{ github.event.inputs.app_namespace }}"

