name: Test Manual Trigger

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: true
        default: 'hello'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input
        run: |
          echo "Input was: ${{ github.event.inputs.test_input }}"